services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ../containers/prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ../containers/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../containers/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../containers/grafana/dashboards:/var/lib/grafana/dashboards
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - "8181:8080"
    volumes:
      - ../containers/wiremock:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--async-response-enabled=true", "--disable-gzip", "--disable-request-logging", "--no-request-journal" ]
