global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: []
#      scheme: http
#      timeout: 10s
#      api_version: v2
scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']